# 数据库连接设置
spring:
    datasource:
#      url: jdbc:mysql://rm-2ze4cv6hn1d37x8537o.mysql.rds.aliyuncs.com:3306/db_fishbuoy
#      jdbc:
#      ?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: wdzhu
#      password: jiuhulu3
      url: jdbc:mysql://localhost:3306/db_fishbuoy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: 132441
      driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        show-sql: true
        properties:
          hibernate:
            format_sql:true
server:
  port: 8181
logging:
  level:
        com.example.fishbuoy: trace