spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aqi?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 132441
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:true
server:
  port: 8181
logging:
  level:
        com.example.fishbuoy: trace